% Run ICA surrounding blinks events
% 2 times: separately for MAG and GRAG, blinks are ordered according to
% correlation with EOG
clearvars;

% Input files
rootdir = '\\\XXX\HierarchicalPriors\data\MEG\brainstorm_database\Unpredict\data\';

% Input files
subjectKEY = {1 'MROS' ; 2 'MRSN' ; 3 'LANR' ; 4 'HLKR' ; 5 'LCBR' ; 6 'MRDG' ; 7 'SMHS' ; 8 'DBBU' ; 9	'PTCR' ; 10 'CRSA' ; 11 'CICE' ;...
    12 'CIBN' ; 13 'FARN' ; 14 'RGBR' ; 15 'LRSU' ; 16 'NNGG' ; 17 'POML' ; 18 'LRVL' ; 19 'SLBG' ; 20 'AAMN' ; 21 'RTKM' ; 22 'SNMN' ;...
    23 'GIMR' ; 24 'ATFC' ; 25 'MRVN' ; 26 'LCTY' ; 27 'JNFN' ; 28 'RBTM' ; 29 'SLML' ; 30 'ANDA' ; 31 'LLMS' ; 32 'AKAL' ; 33 'TTMD' ;...
    34 'ANDL' ; 35 'NCGR' ; 36 'RTDC' ; 37 'PTCS' ; 38 'GGSI' ; 39 'AGCI' ; 40 'ANVC' ; 41 'DNCC' ; 42 'CAOM' ; 43 'MRBU'};

SubjectNames = subjectKEY(:,2)';

for isub = 10
    
    sub = SubjectNames{isub};
    
    runfolders = dir([rootdir sub filesep '*resample*']);
    sFiles = cell(1,length(runfolders));
    for irun=1:length(runfolders)
        runfile = dir([rootdir sub filesep runfolders(irun).name filesep '*raw*']);
        sFiles{1,irun} = [sub filesep runfolders(irun).name filesep runfile.name];
    end
    
    EOGchan = 'EEG063';

    % Start a new report
    bst_report('Start', sFiles);
    
    % Process: ICA components: Infomax
    sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
        'timewindow',   [], ...
        'eventname',    '', ...
        'eventtime',    [-0.2, 0.2], ...%ignore if no eventname
        'resample',     250, ...
        'bandpass',     [1, 100], ...
        'nicacomp',     20, ...
        'sensortypes',  'MEG MAG', ...
        'icasort',      EOGchan, ...
        'usessp',       1, ...
        'ignorebad',    1, ...
        'saveerp',      0, ...
        'method',       1);  % Infomax:    EEGLAB / RunICA
    
    % Process: ICA components: Infomax
    sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
        'timewindow',   [], ...
        'eventname',    '', ...
        'eventtime',    [-0.2, 0.2], ...%ignore if no eventname
        'resample',     250, ...
        'bandpass',     [1, 100], ...
        'nicacomp',     20, ...
        'sensortypes',  'MEG GRAD', ...
        'icasort',      EOGchan, ...
        'usessp',       1, ...
        'ignorebad',    1, ...
        'saveerp',      0, ...
        'method',       1);  % Infomax:    EEGLAB / RunICA
    
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
end
